---
title: "Reproducible Analytical Pipeline"
author: "Joseph Crispell & Nathan Begbie"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: 
  ioslides_presentation:
    logo: Images/DataScienceCampus_logo_square.png
    widescreen: true
    css: css/table.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- Extra custom code to add "OFFICIAL" into the header -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<script>
    $(document).ready(function() {
      $('slide:not(.title-slide, .backdrop, .segue)').append('<header label=\"OFFICIAL\"></header>');    
    })
</script>

<style>
  header:after {
    content: attr(label);
    font-size: 12pt;
    position: absolute;
    top: 10px;
    left: 10px;
    line-height: 1.9;
  }
</style>

<!-- END custom code block for header -->


<!-- TO DO

- Copy in content from Nathan's slides
- Thinking of hypothetical project to update into RAP - refer to throughout

-->

## What we did before

Issues relating to this method:

- Human intensive
- Many points of failure
- Undocumented
- Time consuming and difficult to reproduce

## The Reproducible Analytical Pipeline (RAP) way

INSERT FIGURE

DATA STORE -> SQL -> R/Python -> HTML/PDF/Web application

- All underpinned by version control

## Is it Data Science

NO

It is what underpins data science

- Coding
- Version control
- Reporting

## What do we need?

- Open-source tools
- Version control with `git`
- To consider reproducibility
  
## Why open-source instead of proprietary?

- An online community of users - R and Python are used by millions all over the world
- Free for anyone to use - it is easier to share
- Very powerful and flexible
- Proprietary tools are amazing, powerful and independently maintained but not everyone can access them


## What is version control?

Tracking the three **W**s:

- **W**ho did this?
- **W**hat did they change?
- **W**hy?

A centralised place to store your code.

A decentralised was of writing and developing your code.

`git`

REALLY NICE TURING IMAGE HERE

## Which version control should I use?

| Tool      | Cost | Where?           | Required?         |
| --------- | ---- | ---------------- | ----------------- |
| Github    | Free | Online - Public  |                   |
| Gitlab    | Free | Local            | IT infrastructure |
| Bitbucket | Paid |                  |                   |
| Azure     | Paid | Online - Private |                   |

## What do we mean by reproducible?

In the future, we want to be able to look back at our work today and be able to repeat everything we've done easily

What we need to think about:
- What does our tool depend on?
- What sort of extreme cases could break our tool?
- What is each piece of code doing?

INSERT IMAGES

## Producing the publication

Usually involves writing and interpretation as well as a lot of copying and pasting images. 

Docoments are revised using comments, tracking changes, email, and creating copies

Why not use code to generate your report?

- LaTeX
- Markdown
- Jupyter notebook
- Rmarkdown

## Getting the balance right

Maintenance versus automation

## What are challenges?

- Infrastructure
- Data privacy
- Expertise
- Legacy systems

## Case studies ...

## Mentoring framework

## Useful resources

https://dataingovernment.blog.gov.uk/2017/03/27/reproducible-analytical-pipeline/

https://ukgovdatascience.github.io/rap-website/

https://the-turing-way.netlify.com
